### ISSUE TITLE
Niezły check xd

### ISSUE THREAD

**Issue by radkoder** [KrizzyK/StacjaPaliw#1]
https://github.com/KrizzyK/StacjaPaliw/blob/78b9036acf5fa27862f8dad07c866e245031ae9b/src/project/Main.java#L307

**Comment by KrizzyK** [comment]
Dzięki wielkie. Zanotowałem

**Comment by radkoder** [comment]
Nie dało sie zaincludować całej funkcji ale chodzi o to że sprawdzasz czy jest liczbą przez rzucanie wyjątku xd. Mocny codesmell.

**Comment by KrizzyK** [comment]
Wiem @Ugibugi o co Ci chodziło. Przykra sprawa, że takie coś napisałem. Dla Ciebie jednakże specjalnie zmieniłem ten fragment, pomimo, że projekcik jest zamknięty i piąteczka w dzienniczku xd
